name: Contract Killer
main: com.ftwinston.KillerMinecraft.Modules.ContractKiller.Plugin
depend: [Killer Minecraft]
version: 1
load: STARTUP
description: A game mode for Killer Minecraft
author: FTWinston